Repository assurance-maladie-digital/design-system, pull requests merged in 2021-04, with the labels that each got.

#1010 ✨ vue-dot: Add PageContainer element
  CHANGELOG.md
  packages/vue-dot/src/elements/PageContainer/PageContainer.vue
  packages/vue-dot/src/elements/PageContainer/index.ts
  packages/vue-dot/src/elements/PageContainer/tests/PageContainer.spec.ts
  packages/vue-dot/src/elements/PageContainer/tests/__snapshots__/PageContainer.spec.ts.snap
  packages/vue-dot/src/elements/index.ts
  packages/vue-dot/tests/integration/__snapshots__/libTheme.spec.ts.snap
  packages/vue-dot/tests/integration/__snapshots__/plugin.spec.ts.snap
  packages/vue-dot/tests/integration/__snapshots__/registerAllComponents.spec.ts.snap
Labels: enhancement

#1013 ♻️ docs: Compute prev & next items without position
  packages/docs-v2/src/content/composants/copy-btn.md
  packages/docs-v2/src/content/composants/custom-icon.md
  packages/docs-v2/src/content/composants/data-list-group.md
  packages/docs-v2/src/content/composants/data-list.md
  packages/docs-v2/src/content/composants/date-picker.md
  packages/docs-v2/src/content/composants/dialog-box.md
  packages/docs-v2/src/content/composants/download-btn.md
  packages/docs-v2/src/content/composants/error-page.md
  packages/docs-v2/src/content/composants/file-upload.md
  packages/docs-v2/src/content/composants/footer-wrapper.md
  packages/docs-v2/src/content/composants/form-builder.md
  packages/docs-v2/src/content/composants/form-field-list.md
  packages/docs-v2/src/content/composants/form-field.md
  packages/docs-v2/src/content/composants/header-loading.md
  packages/docs-v2/src/content/composants/lang-btn.md
  packages/docs-v2/src/content/composants/notification-bar.md
  packages/docs-v2/src/content/composants/page-card.md
  packages/docs-v2/src/content/composants/paginated-table.md
  packages/docs-v2/src/content/composants/sub-header.md
  packages/docs-v2/src/content/composants/table-toolbar.md
  packages/docs-v2/src/content/composants/upload-workflow.md
  packages/docs-v2/src/content/demarrer/contribuer.md
  packages/docs-v2/src/content/demarrer/installation.md
  packages/docs-v2/src/content/demarrer/introduction.md
  packages/docs-v2/src/content/directives/debounce.md
  packages/docs-v2/src/content/guides/nouveau-composant.md
  packages/docs-v2/src/content/guides/nouvelle-page.md
  packages/docs-v2/src/content/guides/validation-formulaire.md
  packages/docs-v2/src/content/index.md
  packages/docs-v2/src/content/starter-kit/explorer.md
  packages/docs-v2/src/functions/getSurroundDrawerItems.ts
  packages/docs-v2/src/functions/getSurroundDrawerItemsPaths.ts
  packages/docs-v2/src/pages/_.vue
  packages/docs-v2/src/types/content.d.ts
  packages/docs-v2/src/types/drawer.d.ts
Labels: refactoring

#1024 ✨ vue-dot: Add color prop in PageContainer
  CHANGELOG.md
  packages/vue-dot/src/elements/PageContainer/PageContainer.vue
  packages/vue-dot/src/elements/PageContainer/tests/__snapshots__/PageContainer.spec.ts.snap
Labels: enhancement

#1031 ⬆️ vue-dash: Upgrade dependencies
  CHANGELOG.md
  packages/vue-cli-plugin-vue-dash/generator/functions/extendPackage.js
Labels: dependencies

#1032 📝 Update CHANGELOG
  CHANGELOG.md
Labels: documentation

#1038 🔧 Use cimg/node instead of circleci/node in CircleCI config
  .circleci/config.yml
  CHANGELOG.md
Labels: internal

#1040 🐛 vue-dot: Fix spacing on last item in DataList
  CHANGELOG.md
  packages/vue-dot/src/elements/DataList/DataList.vue
  packages/vue-dot/src/elements/DataList/DataListLoading/DataListLoading.vue
  packages/vue-dot/src/elements/DataList/DataListLoading/tests/__snapshots__/DataListLoading.spec.ts.snap
  packages/vue-dot/src/elements/DataList/tests/__snapshots__/DataList.spec.ts.snap
Labels: bug

#1043 ⬆️ vue-dash: Upgrade dependencies
  CHANGELOG.md
  packages/vue-cli-plugin-vue-dash/generator/functions/extendPackage.js
Labels: dependencies

#1044 📝 Update CHANGELOG
  CHANGELOG.md
Labels: documentation

#1045 🔥 Remove gitHead properties in package.json files
  CHANGELOG.md
  packages/cli-helpers/package.json
  packages/form-builder/package.json
  packages/vue-cli-plugin-vue-dash/package.json
  packages/vue-dot/package.json
Labels: refactoring

#1048 📱 vue-dot: Fix DownloadBtn on small screens
  CHANGELOG.md
  packages/vue-dot/src/elements/DownloadBtn/DownloadBtn.vue
  packages/vue-dot/src/elements/DownloadBtn/config.ts
  packages/vue-dot/src/elements/DownloadBtn/tests/__snapshots__/DownloadBtn.spec.ts.snap
Labels: bug

#1062 ♻️ vue-dot: Use PageContainer in ErrorPage
  packages/vue-dot/src/templates/ErrorPage/ErrorPage.vue
  packages/vue-dot/src/templates/ErrorPage/tests/ErrorPage.spec.ts
  packages/vue-dot/src/templates/ErrorPage/tests/__snapshots__/ErrorPage.spec.ts.snap
Labels: refactoring

#1060 🐛 vue-dot: Set default pickerDate in birthdate mode in DatePicker
  CHANGELOG.md
  packages/vue-dot/src/patterns/DatePicker/mixins/pickerDate.ts
  packages/vue-dot/src/patterns/DatePicker/mixins/tests/pickerDate.spec.ts
Labels: bug

#1066 🔥 vue-dot: Remove PageCard
  CHANGELOG.md
  packages/vue-dot/src/elements/PageCard/PageCard.vue
  packages/vue-dot/src/elements/PageCard/config.ts
  packages/vue-dot/src/elements/PageCard/index.ts
  packages/vue-dot/src/elements/PageCard/tests/PageCard.spec.ts
  packages/vue-dot/src/elements/PageCard/tests/__snapshots__/PageCard.spec.ts.snap
  packages/vue-dot/src/elements/index.ts
  packages/vue-dot/tests/integration/__snapshots__/libTheme.spec.ts.snap
  packages/vue-dot/tests/integration/__snapshots__/plugin.spec.ts.snap
  packages/vue-dot/tests/integration/__snapshots__/registerAllComponents.spec.ts.snap
Labels: refactoring

#1067 ♻️ vue-dot: Use inner wrapper in PageContainer
  CHANGELOG.md
  packages/vue-dot/src/elements/PageContainer/PageContainer.vue
  packages/vue-dot/src/elements/PageContainer/tests/__snapshots__/PageContainer.spec.ts.snap
Labels: refactoring

#1069 ♻️ vue-dash: Use PageContainer instead of PageCard
  CHANGELOG.md
  packages/vue-cli-plugin-vue-dash/generator/template/src/views/About.vue
  packages/vue-cli-plugin-vue-dash/generator/template/src/views/Home.vue
Labels: refactoring

#1071 🐛 vue-dash: Fix missing vuex dependency in extendPackage
  CHANGELOG.md
  packages/vue-cli-plugin-vue-dash/generator/functions/extendPackage.js
Labels: bug

#1072 ♻️ vue-dash: Rename main.js to main.ts in template
  CHANGELOG.md
  packages/vue-cli-plugin-vue-dash/generator/getResourcesToDelete.js
  packages/vue-cli-plugin-vue-dash/generator/template/src/main.ts
Labels: refactoring

#1073 🐛 vue-dash: Fix missing closing tag in About.vue
  CHANGELOG.md
  packages/vue-cli-plugin-vue-dash/generator/template/src/views/About.vue
Labels: bug

#1074 📝 Update Pull Request template
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
Labels: documentation

#1075 ♻️ vue-dot: Remove deprecated VLayout usage in DataListItem
  CHANGELOG.md
  packages/vue-dot/src/elements/DataList/DataListItem/DataListItem.vue
  packages/vue-dot/src/elements/DataList/DataListItem/config.ts
  packages/vue-dot/src/elements/DataList/DataListItem/tests/__snapshots__/DataListItem.spec.ts.snap
  packages/vue-dot/src/elements/DataList/tests/__snapshots__/DataList.spec.ts.snap
Labels: refactoring

#1076 ♻️ vue-dot: Remove deprecated VLayout usage in FileList
  CHANGELOG.md
  packages/vue-dot/src/patterns/UploadWorkflow/FileList/FileList.vue
  packages/vue-dot/src/patterns/UploadWorkflow/FileList/config.ts
  packages/vue-dot/src/patterns/UploadWorkflow/FileList/tests/__snapshots__/FileList.spec.ts.snap
Labels: refactoring

#1077 🔥 Remove useless div in playgrounds
  CHANGELOG.md
  packages/form-builder/dev/App.vue
  packages/vue-dot/dev/App.vue
Labels: refactoring

#1078 🔥 vue-dot: Remove useless layout options in SubHeader
  CHANGELOG.md
  packages/vue-dot/src/patterns/SubHeader/SubHeader.vue
  packages/vue-dot/src/patterns/SubHeader/config.ts
  packages/vue-dot/src/patterns/SubHeader/tests/__snapshots__/SubHeader.spec.ts.snap
Labels: refactoring

#1081 ♻️ form-builder: Remove deprecated VLayout usage in PeriodField
  CHANGELOG.md
  packages/form-builder/src/components/FormBuilder/tests/__snapshots__/FormBuilder.spec.ts.snap
  packages/form-builder/src/components/FormField/fields/PeriodField.vue
Labels: refactoring

#1082 🐛 Fix playgrounds
  CHANGELOG.md
  packages/form-builder/dev/App.vue
  packages/form-builder/dev/form-builder.ts
  packages/form-builder/dev/main.ts
  packages/vue-dot/dev/App.vue
Labels: bug, refactoring
