Repository assurance-maladie-digital/design-system, pull requests merged in 2021-07, with the labels that each got.

#1203 🐛 vue-dot: Fix click:list-item event not working in SubHeader
  CHANGELOG.md
  packages/vue-dot/src/patterns/SubHeader/SubHeader.vue
Labels: bug

#1205 ♻️ vue-dot: Update default suffix value in PaginatedTable
  CHANGELOG.md
  packages/vue-dot/src/patterns/PaginatedTable/PaginatedTable.vue
Labels: refactoring

#1208 🐛 form-builder: Fix input width in PeriodField
  CHANGELOG.md
  packages/form-builder/src/components/FormBuilder/tests/__snapshots__/FormBuilder.spec.ts.snap
  packages/form-builder/src/components/FormField/fields/PeriodField.vue
Labels: bug

#1211 🐛 form-builder: Fix inner spacing in ChoiceButtonField
  CHANGELOG.md
  packages/form-builder/src/components/FormBuilder/tests/__snapshots__/FormBuilder.spec.ts.snap
  packages/form-builder/src/components/FormField/fields/ChoiceButtonField.vue
  packages/form-builder/src/components/FormField/fields/tests/__snapshots__/ChoiceField.spec.ts.snap
Labels: bug

#1212 🐛 vue-dot: Fix resize cursor position in textarea fields
  CHANGELOG.md
  packages/vue-dot/src/styles/vuetify.scss
Labels: bug

#1214 🐛 vue-dot: Fix add button spacing in TableToolbar
  CHANGELOG.md
  packages/vue-dot/src/patterns/TableToolbar/config.ts
  packages/vue-dot/src/patterns/TableToolbar/tests/__snapshots__/TableToolbar.spec.ts.snap
Labels: bug

#1215 🐛 vue-dot: Fix add button icon spacing in TableToolbar
  CHANGELOG.md
  packages/vue-dot/src/patterns/TableToolbar/config.ts
  packages/vue-dot/src/patterns/TableToolbar/tests/__snapshots__/TableToolbar.spec.ts.snap
Labels: bug

#1216 🐛 vue-dot: Fix z-index value in ExternalLinks
  CHANGELOG.md
  packages/vue-dot/src/elements/ExternalLinks/ExternalLinks.vue
  packages/vue-dot/src/elements/ExternalLinks/config.ts
  packages/vue-dot/src/elements/ExternalLinks/tests/__snapshots__/ExternalLinks.spec.ts.snap
Labels: bug

#1218 🐛 vue-dot: Fix button on mobile in ExternalLinks
  CHANGELOG.md
  packages/vue-dot/src/elements/ExternalLinks/ExternalLinks.vue
Labels: bug

#1245 📝 docs: Add RangeField
  CHANGELOG.md
  packages/docs/src/content/composants/form-field.md
  packages/docs/src/content/examples/form-field/range.vue
  packages/docs/src/data/api/form-field.ts
Labels: documentation

#1243 ✨docs: Add RoadmapItem component
  packages/docs/src/components/global/DocRoadmapItem.vue
  packages/docs/src/data/roadmap/labelMapping.ts
  packages/docs/src/types/roadmap.d.ts
Labels: documentation
