Repository assurance-maladie-digital/design-system, pull requests merged in 2021-02, with the labels that each got.

#858 ✨ docs: Add ContentExplorer
  packages/docs-v2/src/assets/styles/utilities.scss
  packages/docs-v2/src/components/SearchField.vue
  packages/docs-v2/src/components/content-explorer/ContentExplorer.vue
  packages/docs-v2/src/components/content-explorer/types.d.ts
  packages/docs-v2/src/components/global/DocContentExplorer.vue
  packages/docs-v2/src/content/explorer/no-content.md
  packages/docs-v2/src/content/explorer/todo.md
  packages/docs-v2/src/content/starter-kit/explorer.md
  packages/docs-v2/src/data/contentExplorerItems.ts
  packages/docs-v2/src/data/drawerItems.ts
  packages/docs-v2/src/global.d.ts
  packages/docs-v2/src/pages/index.vue
Labels: documentation, enhancement

#872 ✨ vue-dot: Add default icons in NotificationBar
  CHANGELOG.md
  packages/vue-dot/src/modules/notification/types.d.ts
  packages/vue-dot/src/patterns/NotificationBar/NotificationBar.vue
  packages/vue-dot/src/patterns/NotificationBar/tests/NotificationBar.spec.ts
  packages/vue-dot/src/patterns/NotificationBar/tests/__snapshots__/NotificationBar.spec.ts.snap
Labels: enhancement

#859 🐛 vue-dot: Handle timezones in DatePicker & parseDate helper
  packages/vue-dot/playground/examples/DatePickerEx.vue
  packages/vue-dot/src/helpers/parseDate/index.ts
  packages/vue-dot/src/helpers/parseDate/tests/parseDate.spec.ts
  packages/vue-dot/src/patterns/DatePicker/mixins/dateLogic.ts
Labels: bug

#822 🔧 vue-dot: Update build limit size
  CHANGELOG.md
  packages/vue-dot/vue.config.js
Labels: internal

#781 ✨ vue-dot: Add DownloadFile element & downloadFile function
  CHANGELOG.md
  package.json
  packages/vue-dot/package.json
  packages/vue-dot/playground/Playground.vue
  packages/vue-dot/playground/examples/DownloadBtnEx.vue
  packages/vue-dot/playground/examples/index.ts
  packages/vue-dot/src/constants/enums/StateEnum.ts
  packages/vue-dot/src/elements/DownloadBtn/DownloadBtn.vue
  packages/vue-dot/src/elements/DownloadBtn/config.ts
  packages/vue-dot/src/elements/DownloadBtn/index.ts
  packages/vue-dot/src/elements/DownloadBtn/locales.ts
  packages/vue-dot/src/elements/DownloadBtn/tests/DownloadBtn.spec.ts
  packages/vue-dot/src/elements/DownloadBtn/tests/__snapshots__/DownloadBtn.spec.ts.snap
  packages/vue-dot/src/elements/DownloadBtn/tests/data/filePromise.ts
  packages/vue-dot/src/elements/DownloadBtn/types.d.ts
  packages/vue-dot/src/elements/index.ts
  packages/vue-dot/src/functions/downloadFile/index.ts
  packages/vue-dot/src/functions/downloadFile/tests/downloadFile.spec.ts
  packages/vue-dot/src/functions/downloadFile/types.d.ts
  packages/vue-dot/src/modules/notification/tests/notify.spec.ts
  packages/vue-dot/tests/integration/__snapshots__/libTheme.spec.ts.snap
  packages/vue-dot/tests/integration/__snapshots__/plugin.spec.ts.snap
  packages/vue-dot/tests/integration/__snapshots__/registerAllComponents.spec.ts.snap
  packages/vue-dot/tsconfig.json
  yarn.lock
Labels: enhancement

#812 ✨ vue-dot: Pass down VTextField slots in DatePicker
  CHANGELOG.md
  packages/vue-dot/playground/examples/DatePickerEx.vue
  packages/vue-dot/playground/theme/theme.scss
  packages/vue-dot/src/patterns/DatePicker/DatePicker.vue
Labels: enhancement

#908 🐛 vue-dot: Fix spacing on prepend slot in DatePicker
  CHANGELOG.md
  packages/form-builder/src/components/FormBuilder/tests/__snapshots__/FormBuilder.spec.ts.snap
  packages/vue-dot/src/patterns/DatePicker/DatePicker.vue
Labels: bug
