Repository assurance-maladie-digital/design-system, pull requests merged in 2021-05, with the labels that each got.

#1106 🔧 Update renovate configuration
  CHANGELOG.md
  renovate.json
Labels: internal

#1110 🚨 vue-dash: Fix lint warnings
  CHANGELOG.md
  packages/vue-cli-plugin-vue-dash/generator/functions/extendPackage.js
  packages/vue-cli-plugin-vue-dash/generator/template/public/index.html
Labels: refactoring

#1121 ⬆️ vue-dash: Upgrade dependencies
  CHANGELOG.md
  packages/vue-cli-plugin-vue-dash/generator/functions/extendPackage.js
Labels: dependencies

#1122 📝 Update CHANGELOG
  CHANGELOG.md
Labels: documentation

#1112 ✨ form-builder: Add RangeField
  CHANGELOG.md
  packages/form-builder/src/components/FormField/fields/RangeField.vue
  packages/form-builder/src/components/FormField/mixins/fieldMap.ts
  packages/form-builder/src/components/FormField/mixins/tests/__snapshots__/fieldMap.spec.ts.snap
  packages/form-builder/src/components/FormField/types.d.ts
Labels: enhancement

#1130 🚨 Fix lint warnings
  CHANGELOG.md
  packages/form-builder/src/components/FormField/fields/ChoiceSliderField.vue
  packages/vue-cli-plugin-vue-dash/vueDotLoader.js
  packages/vue-dot/src/mixins/customizable/index.ts
  packages/vue-dot/tests/utils/addVApp.ts
Labels: internal

#1136 🐛 form-builder: Fix value not resetting in some fields
  CHANGELOG.md
  packages/form-builder/src/components/FormField/fields/ChoiceField.vue
  packages/form-builder/src/components/FormField/fields/PeriodField.vue
  packages/form-builder/src/components/FormField/fields/RangeField.vue
Labels: bug

#1138 🐛 vue-dot: Fix deepCopy not copying falsy values
  CHANGELOG.md
  packages/vue-dot/src/helpers/deepCopy/index.ts
  packages/vue-dot/src/helpers/deepCopy/tests/deepCopy.spec.ts
Labels: bug

#1139 🔧 vue-dot: Update build limit size
  CHANGELOG.md
  packages/vue-dot/vue.config.js
Labels: internal

#1102 ✨ vue-dot: Add FilterModule
  CHANGELOG.md
  packages/vue-dot/package.json
  packages/vue-dot/src/patterns/FilterModule/FilterManager/FilterManager.vue
  packages/vue-dot/src/patterns/FilterModule/FilterManager/config.ts
  packages/vue-dot/src/patterns/FilterModule/FilterManager/index.ts
  packages/vue-dot/src/patterns/FilterModule/FilterManager/locales.ts
  packages/vue-dot/src/patterns/FilterModule/FilterManager/tests/FilterManager.spec.ts
  packages/vue-dot/src/patterns/FilterModule/FilterManager/tests/__snapshots__/FilterManager.spec.ts.snap
  packages/vue-dot/src/patterns/FilterModule/FilterManager/types.d.ts
  packages/vue-dot/src/patterns/FilterModule/FilterModule.vue
  packages/vue-dot/src/patterns/FilterModule/FilterSelector/FilterSelector.vue
  packages/vue-dot/src/patterns/FilterModule/FilterSelector/config.ts
  packages/vue-dot/src/patterns/FilterModule/FilterSelector/index.ts
  packages/vue-dot/src/patterns/FilterModule/FilterSelector/locales.ts
  packages/vue-dot/src/patterns/FilterModule/FilterSelector/tests/FilterSelector.spec.ts
  packages/vue-dot/src/patterns/FilterModule/FilterSelector/tests/__snapshots__/FilterSelector.spec.ts.snap
  packages/vue-dot/src/patterns/FilterModule/config.ts
  packages/vue-dot/src/patterns/FilterModule/index.ts
  packages/vue-dot/src/patterns/FilterModule/locales.ts
  packages/vue-dot/src/patterns/FilterModule/tests/FilterModule.spec.ts
  packages/vue-dot/src/patterns/FilterModule/tests/__snapshots__/FilterModule.spec.ts.snap
  packages/vue-dot/src/patterns/index.ts
  packages/vue-dot/tests/integration/__snapshots__/libTheme.spec.ts.snap
  packages/vue-dot/tests/integration/__snapshots__/plugin.spec.ts.snap
  packages/vue-dot/tests/integration/__snapshots__/registerAllComponents.spec.ts.snap
Labels: enhancement
