Repository assurance-maladie-digital/design-system, pull requests merged in 2021-06, with the labels that each got.

#1157 📌 Pin dependency sass to 1.32.13
  CHANGELOG.md
  package.json
  yarn.lock
Labels: dependencies

#1105 ✨ vue-dot: Add ExternalLinks element
  CHANGELOG.md
  packages/vue-dot/src/elements/ExternalLinks/ExternalLinks.vue
  packages/vue-dot/src/elements/ExternalLinks/PositionEnum.ts
  packages/vue-dot/src/elements/ExternalLinks/config.ts
  packages/vue-dot/src/elements/ExternalLinks/index.ts
  packages/vue-dot/src/elements/ExternalLinks/locales.ts
  packages/vue-dot/src/elements/ExternalLinks/tests/ExternalLinks.spec.ts
  packages/vue-dot/src/elements/ExternalLinks/tests/__snapshots__/ExternalLinks.spec.ts.snap
  packages/vue-dot/src/elements/ExternalLinks/types.d.ts
  packages/vue-dot/src/elements/index.ts
  packages/vue-dot/tests/integration/__snapshots__/libTheme.spec.ts.snap
  packages/vue-dot/tests/integration/__snapshots__/plugin.spec.ts.snap
  packages/vue-dot/tests/integration/__snapshots__/registerAllComponents.spec.ts.snap
Labels: enhancement

#1163 🎨 vue-dot: Use IndexObject instead of custom types
  CHANGELOG.md
  packages/vue-dot/src/helpers/registerComponents/index.ts
  packages/vue-dot/src/mixins/widthable/index.ts
Labels: internal, refactoring

#1164 🎨 vue-dot: Improve code quality
  CHANGELOG.md
  packages/vue-dot/src/elements/DialogBox/DialogBox.vue
  packages/vue-dot/src/patterns/FileUpload/FileUpload.vue
  packages/vue-dot/src/patterns/FileUpload/mixins/fileValidation.ts
Labels: internal, refactoring

#1181 ⬆️ vue-dash: Upgrade dependencies
  CHANGELOG.md
  packages/vue-cli-plugin-vue-dash/generator/functions/extendPackage.js
Labels: dependencies

#1182 📝 Update CHANGELOG
  CHANGELOG.md
Labels: documentation

#1183 🔧 vue-dot: Update build limit size
  CHANGELOG.md
  packages/vue-dot/vue.config.js
Labels: internal

#1193 ♻️ form-builder: Refactor ChoiceSliderField
  CHANGELOG.md
  packages/form-builder/src/components/FormBuilder/tests/__snapshots__/FormBuilder.spec.ts.snap
  packages/form-builder/src/components/FormField/fields/ChoiceSliderField.vue
Labels: refactoring

#1194 🐛 form-builder: Fix tick styles in ChoiceSliderField
  CHANGELOG.md
  packages/form-builder/src/components/FormField/fields/ChoiceSliderField.vue
Labels: bug
