Repository assurance-maladie-digital/design-system, pull requests merged in 2023-05, with the labels that each got.

#2776 🐛 vue-dot: Fix defaultSocialMediaLinks import in FooterBar
  packages/vue-dot/src/patterns/FooterBar/FooterBar.vue
  packages/vue-dot/src/patterns/FooterBar/defaultSocialMediaLinks.ts
Labels: bug

#2777 🐛 docs: Fix typo in FormField example
  packages/docs/src/content/composants/formulaires/form-field.md
Labels: bug

#2778 🐛 vue-dot: Fix VRow max-width
  packages/vue-dot/src/styles/vuetify.scss
Labels: bug

#2779 🐛 vue-dot: Fix Nuxt import in LogoBrandSection
  packages/vue-dot/src/elements/LogoBrandSection/LogoBrandSection.vue
Labels: bug

#2780 🚨 vue-dot: Fix lint warnings
  packages/vue-dot/src/functions/downloadFile/index.ts
  packages/vue-dot/src/mixins/customizable/index.ts
  packages/vue-dot/src/patterns/RatingPicker/tests/RatingMixin.spec.ts
  packages/vue-dot/tests/integration/utils/filterVueInstance.ts
  packages/vue-dot/tests/integration/utils/index.ts
  packages/vue-dot/tests/utils/addVApp.ts
Labels: refactoring

#2781 📝 Update CHANGELOG
  CHANGELOG.md
Labels: documentation

#2766 ♿️ vue-dot: Fix default overlay color
  packages/vue-dot/src/styles/vuetify.scss
Labels: a11y

#2761 ✨ vue-dot: Add slot for content in MaintenancePage
  packages/docs/src/content/templates/maintenance-page.md
  packages/docs/src/data/api/maintenance-page.ts
  packages/docs/src/data/examples/maintenance-page/slots.vue
  packages/vue-dot/src/templates/MaintenancePage/MaintenancePage.vue
Labels: enhancement

#2782 ✨ vue-dot: Add dark prop to BackBtn
  packages/docs/src/content/composants/boutons/back-btn.md
  packages/docs/src/data/api/back-btn.ts
  packages/docs/src/data/examples/back-btn/dark.vue
  packages/docs/src/data/examples/back-btn/usage.vue
  packages/vue-dot/src/elements/BackBtn/BackBtn.vue
Labels: enhancement

#2698 ✨ vue-dot: Add brand-content slot in HeaderBar
  packages/docs/src/content/composants/structure/header-bar.md
  packages/docs/src/data/api/header-bar.ts
  packages/docs/src/data/api/logo.ts
  packages/docs/src/data/examples/header-bar/brand-content.vue
  packages/vue-dot/src/elements/LogoBrandSection/LogoBrandSection.vue
  packages/vue-dot/src/elements/LogoBrandSection/tests/__snapshots__/LogoBrandSection.spec.ts.snap
  packages/vue-dot/src/patterns/HeaderBar/HeaderBar.vue
  packages/vue-dot/src/patterns/HeaderBar/tests/__snapshots__/HeaderBar.spec.ts.snap
Labels: enhancement

#2723 ✨ vue-dot: Add content slots in HeaderBar
  packages/docs/src/content/composants/structure/header-bar.md
  packages/docs/src/data/api/header-bar.ts
  packages/docs/src/data/examples/header-bar/drawer-slots.vue
  packages/docs/src/data/examples/header-bar/navigation-bar-slots.vue
  packages/vue-dot/src/patterns/HeaderBar/HeaderBar.vue
  packages/vue-dot/src/patterns/HeaderBar/HeaderNavigationBar/HeaderNavigationBar.vue
  packages/vue-dot/src/patterns/HeaderBar/HeaderNavigationBar/config.ts
  packages/vue-dot/src/patterns/HeaderBar/HeaderNavigationBar/tests/__snapshots__/HeaderNavigationBar.spec.ts.snap
  packages/vue-dot/src/patterns/HeaderBar/HeaderNavigationDrawer/HeaderNavigationDrawer.vue
  packages/vue-dot/src/patterns/HeaderBar/tests/__snapshots__/HeaderBar.spec.ts.snap
Labels: enhancement

#2824 🐛 vue-dot: Fix item overflow in ContextualMenu
  packages/vue-dot/src/patterns/ContextualMenu/ContextualMenu.vue
  packages/vue-dot/src/patterns/ContextualMenu/tests/__snapshots__/ContextualMenu.spec.ts.snap
Labels: bug, development

#2724 🐛 vue-dot: Fix VAlert styles with type prop
  packages/docs/src/components/global/DocAlert.vue
  packages/vue-dot/src/styles/v-alert.scss
  packages/vue-dot/src/styles/vuetify.scss
Labels: bug
