Repository assurance-maladie-digital/design-system, pull requests merged in 2023-06, with the labels that each got.

#2795 ♿️ vue-dot: Improve RatingPicker accessibility
  packages/vue-dot/src/patterns/RatingPicker/EmotionPicker/EmotionPicker.vue
  packages/vue-dot/src/patterns/RatingPicker/EmotionPicker/tests/__snapshots__/EmotionPicker.spec.ts.snap
  packages/vue-dot/src/patterns/RatingPicker/NumberPicker/NumberPicker.vue
  packages/vue-dot/src/patterns/RatingPicker/NumberPicker/locales.ts
  packages/vue-dot/src/patterns/RatingPicker/NumberPicker/tests/__snapshots__/NumberPicker.spec.ts.snap
  packages/vue-dot/src/patterns/RatingPicker/RatingPicker.vue
  packages/vue-dot/src/patterns/RatingPicker/StarsPicker/StarsPicker.vue
  packages/vue-dot/src/patterns/RatingPicker/StarsPicker/tests/__snapshots__/StarsPicker.spec.ts.snap
  packages/vue-dot/src/patterns/RatingPicker/tests/RatingPicker.spec.ts
  packages/vue-dot/src/patterns/RatingPicker/tests/__snapshots__/RatingPicker.spec.ts.snap
Labels: a11y

#2840 ♻️ vue-dot: Refactor FranceConnectBtn & add connect-plus prop
  packages/docs/src/data/api/france-connect-btn.ts
  packages/docs/src/data/examples/france-connect-btn/usage.vue
  packages/vue-dot/src/elements/FranceConnectBtn/FranceConnectBtn.vue
  packages/vue-dot/src/elements/FranceConnectBtn/locales.ts
  packages/vue-dot/src/elements/FranceConnectBtn/tests/FranceConnectBtn.spec.ts
  packages/vue-dot/src/elements/FranceConnectBtn/tests/__snapshots__/FranceConnectBtn.spec.ts.snap
Labels: refactoring

#2855 ✨ vue-dot: Add matchPattern rule
  packages/docs/src/content/composants-techniques/regles-de-validation/match-pattern.md
  packages/docs/src/data/api/rules/match-pattern.ts
  packages/docs/src/data/drawerItems.ts
  packages/vue-dot/src/rules/matchPattern/index.ts
  packages/vue-dot/src/rules/matchPattern/locales.ts
  packages/vue-dot/src/rules/matchPattern/tests/matchPattern.spec.ts
Labels: enhancement

#2847 📝 docs: Add method & event unit tests examples
  packages/docs/src/content/guides/tests-unitaires.md
Labels: documentation

#2737 ♻️ vue-dash: Remove font loader plugin & add Source Sans 3
  packages/vue-cli-plugin-vue-dash/generator/functions/extendPackage.js
  packages/vue-cli-plugin-vue-dash/generator/template/public/css/base.css
  packages/vue-cli-plugin-vue-dash/generator/template/src/main.ts
  packages/vue-cli-plugin-vue-dash/generator/template/src/plugins/webfontloader.ts
  packages/vue-cli-plugin-vue-dash/generator/template/src/styles/fonts.scss
  packages/vue-cli-plugin-vue-dash/generator/template/src/styles/fonts/OFL.txt
  packages/vue-cli-plugin-vue-dash/generator/template/src/styles/fonts/Source_Sans_3/SourceSans3-Black.woff
  packages/vue-cli-plugin-vue-dash/generator/template/src/styles/fonts/Source_Sans_3/SourceSans3-Black.woff2
  packages/vue-cli-plugin-vue-dash/generator/template/src/styles/fonts/Source_Sans_3/SourceSans3-Bold.woff
  packages/vue-cli-plugin-vue-dash/generator/template/src/styles/fonts/Source_Sans_3/SourceSans3-Bold.woff2
  packages/vue-cli-plugin-vue-dash/generator/template/src/styles/fonts/Source_Sans_3/SourceSans3-ExtraBold.woff
  packages/vue-cli-plugin-vue-dash/generator/template/src/styles/fonts/Source_Sans_3/SourceSans3-ExtraBold.woff2
  packages/vue-cli-plugin-vue-dash/generator/template/src/styles/fonts/Source_Sans_3/SourceSans3-ExtraLight.woff
  packages/vue-cli-plugin-vue-dash/generator/template/src/styles/fonts/Source_Sans_3/SourceSans3-ExtraLight.woff2
  packages/vue-cli-plugin-vue-dash/generator/template/src/styles/fonts/Source_Sans_3/SourceSans3-Italic.woff
  packages/vue-cli-plugin-vue-dash/generator/template/src/styles/fonts/Source_Sans_3/SourceSans3-Italic.woff2
  packages/vue-cli-plugin-vue-dash/generator/template/src/styles/fonts/Source_Sans_3/SourceSans3-Light.woff
  packages/vue-cli-plugin-vue-dash/generator/template/src/styles/fonts/Source_Sans_3/SourceSans3-Light.woff2
  packages/vue-cli-plugin-vue-dash/generator/template/src/styles/fonts/Source_Sans_3/SourceSans3-Medium.woff
  packages/vue-cli-plugin-vue-dash/generator/template/src/styles/fonts/Source_Sans_3/SourceSans3-Medium.woff2
  packages/vue-cli-plugin-vue-dash/generator/template/src/styles/fonts/Source_Sans_3/SourceSans3-Regular.woff
  packages/vue-cli-plugin-vue-dash/generator/template/src/styles/fonts/Source_Sans_3/SourceSans3-Regular.woff2
  packages/vue-cli-plugin-vue-dash/generator/template/src/styles/fonts/Source_Sans_3/SourceSans3-SemiBold.woff
  packages/vue-cli-plugin-vue-dash/generator/template/src/styles/fonts/Source_Sans_3/SourceSans3-SemiBold.woff2
  packages/vue-cli-plugin-vue-dash/generator/template/tsconfig.json
  packages/vue-dot/dev/App.vue
  packages/vue-dot/src/styles/variables.scss
  packages/vue-dot/src/styles/vuetify.scss
Labels: refactoring

#2756 ✨ vue-dot: Add mobile-version prop in UserMenuBtn
  packages/docs/src/data/api/user-menu-btn.ts
  packages/docs/src/data/examples/user-menu-btn/usage.vue
  packages/vue-dot/src/elements/UserMenuBtn/UserMenuBtn.vue
  packages/vue-dot/src/elements/UserMenuBtn/config.ts
  packages/vue-dot/src/elements/UserMenuBtn/tests/__snapshots__/UserMenuBtn.spec.ts.snap
Labels: enhancement

#2901 📝 docs: Move FormBuilder to technical components & add usage explanation
  packages/docs/src/assets/images/components/form-builder.svg
  packages/docs/src/assets/images/components/form-field-list.svg
  packages/docs/src/assets/images/components/form-field.svg
  packages/docs/src/content/composants-techniques/formulaires/form-builder.md
  packages/docs/src/content/composants-techniques/formulaires/form-field-list.md
  packages/docs/src/content/composants-techniques/formulaires/form-field.md
  packages/docs/src/data/componentList.ts
  packages/docs/src/data/drawerItems.ts
Labels: documentation

#2904 🔥 docs: Remove feature request workflow
  .github/ISSUE_TEMPLATE/etude.md
  .github/ISSUE_TEMPLATE/feature_request.md
  packages/docs/src/content/demarrer/contribuer.md
Labels: documentation

#2842 ♻️ docs: Update fonts
  packages/docs/nuxt.config.js
  packages/docs/package.json
  packages/docs/src/assets/styles/base.scss
  packages/docs/src/assets/styles/code-block-theme.scss
  packages/docs/src/assets/styles/fonts.scss
  packages/docs/src/assets/styles/index.scss
  packages/docs/src/static/fonts/Source_Code_Pro/OFL.txt
  packages/docs/src/static/fonts/Source_Code_Pro/SourceCodePro-Bold.woff2
  packages/docs/src/static/fonts/Source_Code_Pro/SourceCodePro-Italic.woff2
  packages/docs/src/static/fonts/Source_Code_Pro/SourceCodePro-Regular.woff2
  packages/docs/src/static/fonts/Source_Code_Pro/SourceCodePro-SemiBold.woff2
  packages/docs/src/static/fonts/Source_Sans_3/OFL.txt
  packages/docs/src/static/fonts/Source_Sans_3/SourceSans3-Black.woff2
  packages/docs/src/static/fonts/Source_Sans_3/SourceSans3-Bold.woff2
  packages/docs/src/static/fonts/Source_Sans_3/SourceSans3-ExtraBold.woff2
  packages/docs/src/static/fonts/Source_Sans_3/SourceSans3-ExtraLight.woff2
  packages/docs/src/static/fonts/Source_Sans_3/SourceSans3-Italic.woff2
  packages/docs/src/static/fonts/Source_Sans_3/SourceSans3-Light.woff2
  packages/docs/src/static/fonts/Source_Sans_3/SourceSans3-Medium.woff2
  packages/docs/src/static/fonts/Source_Sans_3/SourceSans3-Regular.woff2
  packages/docs/src/static/fonts/Source_Sans_3/SourceSans3-SemiBold.woff2
  yarn.lock
Labels: refactoring

#2916 🐛 vue-dot: Fix VOverlay color
  packages/vue-dot/src/styles/vuetify.scss
Labels: development, P1

#2910 🐛 vue-dot: Fix info VAlert colors
  packages/vue-dot/src/styles/v-alert.scss
Labels: bug
