Repository assurance-maladie-digital/design-system, pull requests merged in 2023-04, with the labels that each got.

#2458 ✨ vue-dot: Add CollapsibleList component
  packages/docs/src/content/composants/structure/footer-bar.md
  packages/docs/src/data/examples/footer-bar/collapsible-list.vue
  packages/docs/src/data/roadmap/index.ts
  packages/vue-dot/src/patterns/FooterBar/CollapsibleList/CollapsibleList.vue
  packages/vue-dot/src/patterns/FooterBar/CollapsibleList/index.ts
  packages/vue-dot/src/patterns/FooterBar/CollapsibleList/tests/CollapsibleList.spec.ts
  packages/vue-dot/src/patterns/FooterBar/CollapsibleList/tests/__snapshots__/CollapsibleList.spec.ts.snap
  packages/vue-dot/src/patterns/FooterBar/CollapsibleList/types.d.ts
Labels: Développement

#2679 🐛 vue-dot: Fix HeaderBar drawer rendered on mobile without items
  packages/vue-dot/src/patterns/HeaderBar/HeaderNavigationDrawer/HeaderNavigationDrawer.vue
  packages/vue-dot/src/patterns/HeaderBar/HeaderNavigationDrawer/tests/__snapshots__/HeaderNavigationDrawer.spec.ts.snap
Labels: Bug, Développement

#2685 🔧 Configure GitHub release notes
  .github/release.yml
Labels: configuration

#2680 🐛 vue-dot: Fix duplicated change event in DatePicker
  packages/vue-dot/src/patterns/DatePicker/DatePicker.vue
Labels: bug

#2687 ♻️ vue-dash: Use MaintenancePage & NotFoundPage in template
  packages/vue-cli-plugin-vue-dash/generator/template/jest.config.ts
  packages/vue-cli-plugin-vue-dash/generator/template/src/translations/fr/views/maintenance.ts
  packages/vue-cli-plugin-vue-dash/generator/template/src/translations/fr/views/notFound.ts
  packages/vue-cli-plugin-vue-dash/generator/template/src/views/Maintenance.vue
  packages/vue-cli-plugin-vue-dash/generator/template/src/views/NotFound.vue
Labels: refactoring

#2692 🔧 vue-dot: Update lint configuration
  packages/vue-dot/.eslintrc.js
  packages/vue-dot/package.json
  packages/vue-dot/src/directives/debounce/core.ts
  packages/vue-dot/src/elements/DialogBox/DialogBox.vue
  packages/vue-dot/src/helpers/localStorageUtility/index.ts
  packages/vue-dot/src/modules/notification/notify.ts
  packages/vue-dot/src/patterns/DatePicker/DatePicker.vue
  packages/vue-dot/src/patterns/DatePicker/mixins/dateLogic.ts
  packages/vue-dot/src/patterns/FileUpload/mixins/tests/fileUploadCore.spec.ts
  packages/vue-dot/src/patterns/FilterModule/FilterModule.vue
  packages/vue-dot/src/patterns/NirField/NirField.vue
  packages/vue-dot/src/patterns/RatingPicker/RatingPicker.vue
  packages/vue-dot/src/patterns/RatingPicker/tests/RatingMixin.spec.ts
  packages/vue-dot/src/patterns/UploadWorkflow/mixins/updateFileModel.ts
  packages/vue-dot/src/patterns/UploadWorkflow/mixins/uploadWorkflowCore.ts
  packages/vue-dot/src/rules/minLength/tests/minLength.spec.ts
  yarn.lock
Labels: configuration

#2705 ♻️ vue-dot: Refactor NirField
  packages/docs/src/content/composants/formulaires/nir-field.md
  packages/docs/src/data/api/nir-field.ts
  packages/docs/src/data/examples/nir-field/key.vue
  packages/docs/src/data/examples/nir-field/required.vue
  packages/docs/src/data/examples/nir-field/usage.vue
  packages/vue-dot/src/patterns/NirField/NirField.vue
  packages/vue-dot/src/patterns/NirField/config.ts
  packages/vue-dot/src/patterns/NirField/locales.ts
  packages/vue-dot/src/patterns/NirField/tests/NirField.spec.ts
  packages/vue-dot/src/patterns/NirField/tests/__snapshots__/NirField.spec.ts.snap
Labels: refactoring

#2572 ✨ vue-dot: Add ContextualMenu component
  packages/docs/.eslintrc.js
  packages/docs/src/app/router.scrollBehavior.js
  packages/docs/src/components/global/DocTabs.vue
  packages/docs/src/content/composants/navigation/contextual-menu.md
  packages/docs/src/data/api/contextual-menu.ts
  packages/docs/src/data/drawerItems.ts
  packages/docs/src/data/examples/contextual-menu/levels.vue
  packages/docs/src/data/examples/contextual-menu/usage.vue
  packages/vue-cli-plugin-vue-dash/vueDotLoader.js
  packages/vue-dot/src/patterns/ContextualMenu/ContextualMenu.vue
  packages/vue-dot/src/patterns/ContextualMenu/index.ts
  packages/vue-dot/src/patterns/ContextualMenu/tests/ContextualMenu.spec.ts
  packages/vue-dot/src/patterns/ContextualMenu/tests/__snapshots__/ContextualMenu.spec.ts.snap
  packages/vue-dot/src/patterns/ContextualMenu/types.d.ts
  packages/vue-dot/src/patterns/index.ts
  packages/vue-dot/tests/integration/__snapshots__/libTheme.spec.ts.snap
  packages/vue-dot/tests/integration/__snapshots__/plugin.spec.ts.snap
  packages/vue-dot/tests/integration/__snapshots__/registerAllComponents.spec.ts.snap
Labels: enhancement

#2708 🐛 docs: Fix examples with wrong structure
  packages/docs/src/content/composants/formulaires/nir-field.md
  packages/docs/src/content/composants/formulaires/phone-field.md
  packages/docs/src/content/composants/navigation/external-links.md
  packages/docs/src/content/composants/tableaux/filter-module.md
Labels: bug

#2711 ♻️ vue-dot: Refactor AccessibilityBanner into SkipLink
  packages/docs/src/assets/images/components/accessibility-banner.svg
  packages/docs/src/assets/images/components/contextual-menu.svg
  packages/docs/src/assets/images/components/skip-link.svg
  packages/docs/src/assets/images/placeholder.svg
  packages/docs/src/components/DocComponentList.vue
  packages/docs/src/content/composants/navigation/accessibility-banner.md
  packages/docs/src/content/composants/navigation/contextual-menu.md
  packages/docs/src/content/composants/navigation/skip-link.md
  packages/docs/src/data/api/accessibility-banner.ts
  packages/docs/src/data/api/contextual-menu.ts
  packages/docs/src/data/api/skip-link.ts
  packages/docs/src/data/componentList.ts
  packages/docs/src/data/drawerItems.ts
  packages/docs/src/data/examples/accessibility-banner/options.vue
  packages/docs/src/data/examples/accessibility-banner/usage.vue
  packages/docs/src/data/examples/skip-link/usage.vue
  packages/docs/src/pages/_.vue
  packages/vue-cli-plugin-vue-dash/vueDotLoader.js
  packages/vue-dot/dev/App.vue
  packages/vue-dot/src/elements/SkipLink/SkipLink.vue
  packages/vue-dot/src/elements/SkipLink/index.ts
  packages/vue-dot/src/elements/SkipLink/locales.ts
  packages/vue-dot/src/elements/SkipLink/tests/SkipLink.spec.ts
  packages/vue-dot/src/elements/SkipLink/tests/__snapshots__/SkipLink.spec.ts.snap
  packages/vue-dot/src/elements/index.ts
  packages/vue-dot/src/patterns/AccessibilityBanner/AccessibilityBanner.vue
  packages/vue-dot/src/patterns/AccessibilityBanner/config.ts
  packages/vue-dot/src/patterns/AccessibilityBanner/index.ts
  packages/vue-dot/src/patterns/AccessibilityBanner/locales.ts
  packages/vue-dot/src/patterns/AccessibilityBanner/tests/__snapshots__/AccessibilityBanner.spec.ts.snap
  packages/vue-dot/src/patterns/index.ts
  packages/vue-dot/tests/integration/__snapshots__/libTheme.spec.ts.snap
  packages/vue-dot/tests/integration/__snapshots__/plugin.spec.ts.snap
  packages/vue-dot/tests/integration/__snapshots__/registerAllComponents.spec.ts.snap
Labels: refactoring

#2729 🐛 vue-dot: Fix theme prop default value in LogoBrandSection
  packages/vue-dot/src/elements/LogoBrandSection/LogoBrandSection.vue
Labels: bug

#2728 🐛 vue-dot: Fix link outline in LogoBrandSection
  packages/docs/src/data/examples/logo-brand-section/usage.vue
  packages/vue-dot/src/elements/LogoBrandSection/LogoBrandSection.vue
Labels: bug

#2733 ♻️ vue-dot: Refactor CollapsibleList
  packages/docs/src/data/api/footer-bar.ts
  packages/docs/src/data/examples/footer-bar/collapsible-list.vue
  packages/vue-dot/src/patterns/FooterBar/CollapsibleList/CollapsibleList.vue
  packages/vue-dot/src/patterns/FooterBar/CollapsibleList/tests/CollapsibleList.spec.ts
  packages/vue-dot/src/patterns/FooterBar/CollapsibleList/tests/__snapshots__/CollapsibleList.spec.ts.snap
  packages/vue-dot/src/patterns/FooterBar/CollapsibleList/types.d.ts
Labels: refactoring

#2725 ♻️ vue-dot: Refactor links handling in FooterBar
  packages/docs/src/content/composants/structure/footer-bar.md
  packages/docs/src/data/api/footer-bar.ts
  packages/docs/src/data/examples/footer-bar/collapsible-list.vue
  packages/docs/src/data/examples/footer-bar/content-slots.vue
  packages/docs/src/data/examples/footer-bar/dark.vue
  packages/docs/src/data/examples/footer-bar/default-slot.vue
  packages/docs/src/data/examples/footer-bar/externalsLinks.vue
  packages/docs/src/data/examples/footer-bar/hide-social-media-links.vue
  packages/docs/src/data/examples/footer-bar/link-items.vue
  packages/docs/src/data/examples/footer-bar/options.vue
  packages/docs/src/data/examples/footer-bar/slots.vue
  packages/docs/src/data/examples/footer-bar/social-media-links.vue
  packages/vue-dot/src/patterns/FooterBar/FooterBar.vue
  packages/vue-dot/src/patterns/FooterBar/FooterLink/FooterLink.vue
  packages/vue-dot/src/patterns/FooterBar/FooterLink/index.ts
  packages/vue-dot/src/patterns/FooterBar/FooterLink/tests/FooterLink.spec.ts
  packages/vue-dot/src/patterns/FooterBar/FooterLink/tests/__snapshots__/FooterLink.spec.ts.snap
  packages/vue-dot/src/patterns/FooterBar/SocialMediaLinks/SocialMediaLinks.vue
  packages/vue-dot/src/patterns/FooterBar/SocialMediaLinks/tests/__snapshots__/SocialMediaLinks.spec.ts.snap
  packages/vue-dot/src/patterns/FooterBar/config.ts
  packages/vue-dot/src/patterns/FooterBar/socialMediaLinks.ts
  packages/vue-dot/src/patterns/FooterBar/tests/FooterBar.spec.ts
  packages/vue-dot/src/patterns/FooterBar/tests/__snapshots__/FooterBar.spec.ts.snap
  packages/vue-dot/src/patterns/FooterBar/types.d.ts
Labels: refactoring

#2746 ♻️ docs: Update team in introduction page
  packages/docs/src/assets/images/team/julien_b.jpg
  packages/docs/src/components/global/DocHomePageTeam.vue
  packages/docs/src/constants/index.ts
Labels: refactoring

#2747 ♿️ vue-dot: Add contentinfo role on FooterBar
  packages/vue-dot/src/patterns/FooterBar/FooterBar.vue
  packages/vue-dot/src/patterns/FooterBar/tests/__snapshots__/FooterBar.spec.ts.snap
Labels: a11y

#2752 ♿️ form-builder: Fix aria-label on show password button in PasswordField
  packages/form-builder/src/components/FormBuilder/tests/__snapshots__/FormBuilder.spec.ts.snap
  packages/form-builder/src/components/FormField/fields/PasswordField.vue
Labels: a11y

#2767 🐛 vue-dot: Fix FilePreview options binding in UploadWorkflow
  packages/vue-dot/src/patterns/UploadWorkflow/UploadWorkflow.vue
Labels: bug
