Repository assurance-maladie-digital/design-system, pull requests merged in 2023-09, with the labels that each got.

#3031 🐛 vue-dash: Fix font declaration in template
  packages/vue-cli-plugin-vue-dash/generator/template/public/css/fonts.css
Labels: bug

#3032 🐛 vue-dash: Add missing component in vueDotLoader
  packages/vue-cli-plugin-vue-dash/vueDotLoader.js
Labels: bug

#3033 🐛 vue-dot: Fix SkipLink with HeaderBar
  packages/docs/src/data/examples/skip-link/usage.vue
  packages/vue-dot/src/elements/SkipLink/SkipLink.vue
  packages/vue-dot/src/elements/SkipLink/tests/__snapshots__/SkipLink.spec.ts.snap
  packages/vue-dot/src/styles/components.scss
Labels: bug

#3010 ✨ vue-dot: Add new filter components
  package.json
  packages/docs/package.json
  packages/docs/src/assets/images/components/filters-inline.svg
  packages/docs/src/assets/images/components/filters-sidebar.svg
  packages/docs/src/content/composants/donnees/chip-list.md
  packages/docs/src/content/composants/filtres/filter-module.md
  packages/docs/src/content/composants/filtres/filters-inline.md
  packages/docs/src/content/composants/filtres/filters-side-bar.md
  packages/docs/src/content/composants/formulaires/search-list-field.md
  packages/docs/src/data/api/chip-list.ts
  packages/docs/src/data/api/filters-inline.ts
  packages/docs/src/data/api/filters-side-bar.ts
  packages/docs/src/data/api/rating-picker.ts
  packages/docs/src/data/api/search-list-field.ts
  packages/docs/src/data/api/shared/mixins/filterable.ts
  packages/docs/src/data/api/shared/mixins/rating-mixin.ts
  packages/docs/src/data/componentList.ts
  packages/docs/src/data/drawerItems.ts
  packages/docs/src/data/examples/chip-list/usage.vue
  packages/docs/src/data/examples/filters-inline/chip-format.vue
  packages/docs/src/data/examples/filters-inline/custom-style.vue
  packages/docs/src/data/examples/filters-inline/usage.vue
  packages/docs/src/data/examples/filters-side-bar/chip-format.vue
  packages/docs/src/data/examples/filters-side-bar/custom-style.vue
  packages/docs/src/data/examples/filters-side-bar/usage.vue
  packages/docs/src/data/examples/search-list-field/usage.vue
  packages/vue-cli-plugin-vue-dash/vueDotLoader.js
  packages/vue-dot/src/elements/ChipList/ChipList.vue
  packages/vue-dot/src/elements/ChipList/index.ts
  packages/vue-dot/src/elements/ChipList/locales.ts
  packages/vue-dot/src/elements/ChipList/tests/ChipList.spec.ts
  packages/vue-dot/src/elements/ChipList/tests/__snapshots__/ChipList.spec.ts.snap
  packages/vue-dot/src/elements/ChipList/types.d.ts
  packages/vue-dot/src/elements/index.ts
  packages/vue-dot/src/mixins/filterable/index.ts
  packages/vue-dot/src/mixins/filterable/tests/filterable.spec.ts
  packages/vue-dot/src/mixins/filterable/types.d.ts
  packages/vue-dot/src/patterns/FiltersInline/FiltersInline.vue
  packages/vue-dot/src/patterns/FiltersInline/index.ts
  packages/vue-dot/src/patterns/FiltersInline/locales.ts
  packages/vue-dot/src/patterns/FiltersInline/tests/FiltersInline.spec.ts
  packages/vue-dot/src/patterns/FiltersInline/tests/__snapshots__/FiltersInline.spec.ts.snap
  packages/vue-dot/src/patterns/FiltersSideBar/FiltersSideBar.vue
  packages/vue-dot/src/patterns/FiltersSideBar/index.ts
  packages/vue-dot/src/patterns/FiltersSideBar/locales.ts
  packages/vue-dot/src/patterns/FiltersSideBar/tests/FiltersSideBar.spec.ts
  packages/vue-dot/src/patterns/FiltersSideBar/tests/__snapshots__/FiltersSideBar.spec.ts.snap
  packages/vue-dot/src/patterns/PeriodField/PeriodField.vue
  packages/vue-dot/src/patterns/SearchListField/SearchListField.vue
  packages/vue-dot/src/patterns/SearchListField/index.ts
  packages/vue-dot/src/patterns/SearchListField/locales.ts
  packages/vue-dot/src/patterns/SearchListField/tests/SearchListField.spec.ts
  packages/vue-dot/src/patterns/SearchListField/tests/__snapshots__/SearchListField.spec.ts.snap
  packages/vue-dot/src/patterns/SearchListField/types.d.ts
  packages/vue-dot/src/patterns/index.ts
  packages/vue-dot/tests/integration/__snapshots__/libTheme.spec.ts.snap
  packages/vue-dot/tests/integration/__snapshots__/plugin.spec.ts.snap
  packages/vue-dot/tests/integration/__snapshots__/registerAllComponents.spec.ts.snap
Labels: enhancement

#3040 📝 docs: Add custom sub-path guide
  packages/docs/src/content/composants-techniques/helpers/scroll-behavior.md
  packages/docs/src/content/composants-techniques/helpers/test-utils.md
  packages/docs/src/content/guides/authentification-token.md
  packages/docs/src/content/guides/nouvelle-page.md
  packages/docs/src/content/guides/sous-chemin.md
  packages/docs/src/data/drawerItems.ts
Labels: documentation

#3042 ✨ vue-dot: Add openInNewTab property to FooterBar items
  packages/docs/src/data/api/footer-bar.ts
  packages/docs/src/data/examples/footer-bar/link-items.vue
  packages/vue-dot/src/patterns/FooterBar/FooterBar.vue
  packages/vue-dot/src/patterns/FooterBar/types.d.ts
Labels: enhancement

#3043 ✨ vue-dot: Add PasswordField
  packages/docs/src/assets/images/components/password-field.svg
  packages/docs/src/content/composants/formulaires/password-field.md
  packages/docs/src/data/api/password-field.ts
  packages/docs/src/data/componentList.ts
  packages/docs/src/data/drawerItems.ts
  packages/docs/src/data/examples/password-field/required.vue
  packages/docs/src/data/examples/password-field/usage.vue
  packages/form-builder/src/components/FormBuilder/tests/__snapshots__/FormBuilder.spec.ts.snap
  packages/form-builder/src/components/FormField/fields/FormPasswordField.vue
  packages/form-builder/src/components/FormField/fields/PasswordField.vue
  packages/form-builder/src/components/FormField/mixins/fieldMap.ts
  packages/form-builder/src/components/FormField/mixins/tests/__snapshots__/fieldMap.spec.ts.snap
  packages/form-builder/vue.config.js
  packages/vue-cli-plugin-vue-dash/vueDotLoader.js
  packages/vue-dot/src/patterns/DatePicker/mixins/dateLogic.ts
  packages/vue-dot/src/patterns/PasswordField/PasswordField.vue
  packages/vue-dot/src/patterns/PasswordField/config.ts
  packages/vue-dot/src/patterns/PasswordField/index.ts
  packages/vue-dot/src/patterns/PasswordField/locales.ts
  packages/vue-dot/src/patterns/PasswordField/tests/PasswordField.spec.ts
  packages/vue-dot/src/patterns/PasswordField/tests/__snapshots__/PasswordField.spec.ts.snap
  packages/vue-dot/src/patterns/index.ts
  packages/vue-dot/tests/integration/__snapshots__/libTheme.spec.ts.snap
  packages/vue-dot/tests/integration/__snapshots__/plugin.spec.ts.snap
  packages/vue-dot/tests/integration/__snapshots__/registerAllComponents.spec.ts.snap
Labels: enhancement

#3048 📝 docs: Update component list
  packages/docs/src/assets/images/components/chip-list.svg
  packages/docs/src/assets/images/components/search-list-field.svg
  packages/docs/src/data/componentList.ts
  packages/docs/src/data/templateList.ts
Labels: documentation

#3050 🐛 vue-dot: Fix missing dependency
  packages/vue-dot/package.json
Labels: bug

#3049 ✨ vue-dot: Add validation on PeriodField
  packages/vue-dot/src/patterns/PeriodField/PeriodField.vue
  packages/vue-dot/src/patterns/PeriodField/locales.ts
Labels: enhancement

#3037 ✨ vue-dot: Add show-sticky-nav-bar in HeaderBar
  packages/docs/src/data/api/header-bar.ts
  packages/docs/src/data/examples/header-bar/usage.vue
  packages/vue-dot/src/patterns/HeaderBar/HeaderBar.vue
  packages/vue-dot/src/patterns/HeaderBar/tests/HeaderBar.spec.ts
  packages/vue-dot/src/patterns/HeaderBar/tests/__snapshots__/HeaderBar.spec.ts.snap
Labels: enhancement

#3054 ✨ vue-dot: Add SelectBtnField
  packages/docs/src/assets/images/components/select-btn-field.svg
  packages/docs/src/content/composants-techniques/formulaires/form-field.md
  packages/docs/src/content/composants/formulaires/nir-field.md
  packages/docs/src/content/composants/formulaires/password-field.md
  packages/docs/src/content/composants/formulaires/phone-field.md
  packages/docs/src/content/composants/formulaires/select-btn-field.md
  packages/docs/src/data/api/range-field.ts
  packages/docs/src/data/api/search-list-field.ts
  packages/docs/src/data/api/select-btn-field.ts
  packages/docs/src/data/componentList.ts
  packages/docs/src/data/drawerItems.ts
  packages/docs/src/data/examples/form-field/select-button-other.vue
  packages/docs/src/data/examples/form-field/select-button-unique.vue
  packages/docs/src/data/examples/select-btn-field/error-messages.vue
  packages/docs/src/data/examples/select-btn-field/error.vue
  packages/docs/src/data/examples/select-btn-field/hint.vue
  packages/docs/src/data/examples/select-btn-field/inline.vue
  packages/docs/src/data/examples/select-btn-field/multiple.vue
  packages/docs/src/data/examples/select-btn-field/unique.vue
  packages/docs/src/data/examples/select-btn-field/usage.vue
  packages/form-builder/src/components/FormBuilder/tests/__snapshots__/FormBuilder.spec.ts.snap
  packages/form-builder/src/components/FormField/fields/ChoiceButtonField.vue
  packages/form-builder/src/components/FormField/fields/ChoiceField.vue
  packages/form-builder/src/components/FormField/fields/tests/__snapshots__/ChoiceField.spec.ts.snap
  packages/vue-cli-plugin-vue-dash/vueDotLoader.js
  packages/vue-dot/src/patterns/SelectBtnField/SelectBtnField.vue
  packages/vue-dot/src/patterns/SelectBtnField/config.ts
  packages/vue-dot/src/patterns/SelectBtnField/index.ts
  packages/vue-dot/src/patterns/SelectBtnField/tests/SelectBtnField.spec.ts
  packages/vue-dot/src/patterns/SelectBtnField/tests/__snapshots__/SelectBtnField.spec.ts.snap
  packages/vue-dot/src/patterns/SelectBtnField/types.d.ts
  packages/vue-dot/src/patterns/index.ts
  packages/vue-dot/tests/integration/__snapshots__/libTheme.spec.ts.snap
  packages/vue-dot/tests/integration/__snapshots__/plugin.spec.ts.snap
  packages/vue-dot/tests/integration/__snapshots__/registerAllComponents.spec.ts.snap
Labels: enhancement

#3055 📝 docs: Update roadmap
  packages/docs/src/components/global/DocRoadmap.vue
Labels: documentation

#3062 ✨ vue-dot: Add AlertWrapper pattern
  packages/docs/src/assets/images/components/alert-wrapper.svg
  packages/docs/src/components/global/DocAlert.vue
  packages/docs/src/content/composants/feedback/alert-wrapper.md
  packages/docs/src/data/api/alert-wrapper.ts
  packages/docs/src/data/componentList.ts
  packages/docs/src/data/drawerItems.ts
  packages/docs/src/data/examples/alert-wrapper/dismissible.vue
  packages/docs/src/data/examples/alert-wrapper/usage.vue
  packages/vue-cli-plugin-vue-dash/vueDotLoader.js
  packages/vue-dot/src/patterns/AlertWrapper/AlertTypeEnum.ts
  packages/vue-dot/src/patterns/AlertWrapper/AlertWrapper.vue
  packages/vue-dot/src/patterns/AlertWrapper/index.ts
  packages/vue-dot/src/patterns/AlertWrapper/locales.ts
  packages/vue-dot/src/patterns/AlertWrapper/tests/AlertWrapper.spec.ts
  packages/vue-dot/src/patterns/AlertWrapper/tests/__snapshots__/AlertWrapper.spec.ts.snap
  packages/vue-dot/src/patterns/RatingPicker/RatingPicker.vue
  packages/vue-dot/src/patterns/index.ts
  packages/vue-dot/src/styles/v-alert.scss
  packages/vue-dot/src/styles/vuetify.scss
  packages/vue-dot/tests/integration/__snapshots__/libTheme.spec.ts.snap
  packages/vue-dot/tests/integration/__snapshots__/plugin.spec.ts.snap
  packages/vue-dot/tests/integration/__snapshots__/registerAllComponents.spec.ts.snap
Labels: enhancement

#3063 🔥 docs: Remove ACL guide
  packages/docs/src/content/guides/gestion-droits.md
  packages/docs/src/data/drawerItems.ts
Labels: documentation

#3067 🐛 vue-dot: Fix error icon in NotificationBar
  packages/vue-dot/src/patterns/NotificationBar/NotificationBar.vue
Labels: bug

#3111 ⬇️ Revert dependency @vue/eslint-config-typescript update to v12
  packages/eslint-config-vue/package.json
  yarn.lock
Labels: dependencies

#3113 🐛 vue-dot: Fix missing icon slot in AlertWrapper
  packages/docs/src/data/api/alert-wrapper.ts
  packages/vue-dot/src/patterns/AlertWrapper/AlertWrapper.vue
Labels: bug
