Repository assurance-maladie-digital/design-system, pull requests merged in 2023-07, with the labels that each got.

#2947 ✨ vue-dot: Add aria-label property to link-items in FooterBar
  packages/docs/src/data/api/footer-bar.ts
  packages/docs/src/data/examples/footer-bar/link-items.vue
  packages/vue-dot/src/patterns/FooterBar/CollapsibleList/CollapsibleList.vue
  packages/vue-dot/src/patterns/FooterBar/CollapsibleList/types.d.ts
  packages/vue-dot/src/patterns/FooterBar/FooterBar.vue
  packages/vue-dot/src/patterns/FooterBar/types.d.ts
Labels: enhancement

#2940 ✨ vue-dot: Add mini-version prop to HeaderBar
  packages/docs/src/data/api/header-bar.ts
  packages/docs/src/data/examples/header-bar/usage.vue
  packages/vue-dot/src/patterns/HeaderBar/HeaderBar.vue
  packages/vue-dot/src/patterns/HeaderBar/tests/HeaderBar.spec.ts
  packages/vue-dot/src/patterns/HeaderBar/tests/__snapshots__/HeaderBar.spec.ts.snap
Labels: enhancement

#2960 🐛 vue-dot: Fix SkipLink focus on route change
  packages/vue-dot/src/elements/SkipLink/SkipLink.vue
  packages/vue-dot/src/elements/SkipLink/tests/__snapshots__/SkipLink.spec.ts.snap
Labels: bug

#2977 ♻️ vue-dot: Refactor error pages
  packages/docs/src/content/templates/error-page.md
  packages/docs/src/content/templates/maintenance-page.md
  packages/docs/src/content/templates/not-found-page.md
  packages/docs/src/data/api/error-page.ts
  packages/docs/src/data/api/maintenance-page.ts
  packages/docs/src/data/api/not-found-page.ts
  packages/docs/src/data/examples/error-page/maintenance.vue
  packages/docs/src/data/examples/error-page/not-found.vue
  packages/docs/src/data/examples/error-page/support-id.vue
  packages/docs/src/data/examples/error-page/usage.vue
  packages/docs/src/data/examples/maintenance-page/slots.vue
  packages/docs/src/data/examples/maintenance-page/usage.vue
  packages/docs/src/data/examples/not-found-page/slots.vue
  packages/docs/src/data/examples/not-found-page/usage.vue
  packages/vue-dot/src/templates/ErrorPage/ErrorPage.vue
  packages/vue-dot/src/templates/ErrorPage/tests/__snapshots__/ErrorPage.spec.ts.snap
  packages/vue-dot/src/templates/MaintenancePage/MaintenancePage.vue
  packages/vue-dot/src/templates/MaintenancePage/tests/MaintenancePage.spec.ts
  packages/vue-dot/src/templates/MaintenancePage/tests/__snapshots__/MaintenancePage.spec.ts.snap
  packages/vue-dot/src/templates/NotFoundPage/NotFoundPage.vue
  packages/vue-dot/src/templates/NotFoundPage/locales.ts
  packages/vue-dot/src/templates/NotFoundPage/tests/NotFoundPage.spec.ts
  packages/vue-dot/src/templates/NotFoundPage/tests/__snapshots__/NotFoundPage.spec.ts.snap
Labels: refactoring

#2941 ♻️ vue-dot: Extract FileList component
  packages/docs/src/assets/images/components/file-list.svg
  packages/docs/src/assets/images/components/upload-workflow.svg
  packages/docs/src/content/composants/donnees/file-list.md
  packages/docs/src/content/composants/formulaires/upload-workflow.md
  packages/docs/src/data/api/file-list.ts
  packages/docs/src/data/api/upload-workflow.ts
  packages/docs/src/data/componentList.ts
  packages/docs/src/data/drawerItems.ts
  packages/docs/src/data/examples/file-list/optional.vue
  packages/docs/src/data/examples/file-list/show-view-btn.vue
  packages/docs/src/data/examples/file-list/states.vue
  packages/docs/src/data/examples/file-list/usage.vue
  packages/vue-dot/src/elements/FileList/FileList.vue
  packages/vue-dot/src/elements/FileList/FileStateEnum.ts
  packages/vue-dot/src/elements/FileList/config.ts
  packages/vue-dot/src/elements/FileList/index.ts
  packages/vue-dot/src/elements/FileList/locales.ts
  packages/vue-dot/src/elements/FileList/tests/FileList.spec.ts
  packages/vue-dot/src/elements/FileList/tests/__snapshots__/FileList.spec.ts.snap
  packages/vue-dot/src/elements/FileList/types.d.ts
  packages/vue-dot/src/elements/index.ts
  packages/vue-dot/src/patterns/UploadWorkflow/UploadWorkflow.vue
  packages/vue-dot/src/patterns/UploadWorkflow/tests/__snapshots__/UploadWorkflow.spec.ts.snap
  packages/vue-dot/src/patterns/UploadWorkflow/types.d.ts
  packages/vue-dot/tests/integration/__snapshots__/libTheme.spec.ts.snap
  packages/vue-dot/tests/integration/__snapshots__/plugin.spec.ts.snap
  packages/vue-dot/tests/integration/__snapshots__/registerAllComponents.spec.ts.snap
Labels: refactoring

#2928 ♻️ vue-dot: Add margin for main content & improve tests in HeaderBar
  packages/docs/src/data/examples/header-bar/usage.vue
  packages/vue-dot/src/patterns/HeaderBar/HeaderBar.vue
  packages/vue-dot/src/patterns/HeaderBar/tests/HeaderBar.spec.ts
  packages/vue-dot/src/patterns/HeaderBar/tests/__snapshots__/HeaderBar.spec.ts.snap
Labels: bug

#2993 🐛 vue-dot: Fix UploadWorkflow tests
  packages/vue-dot/src/patterns/UploadWorkflow/tests/UploadWorkflow.spec.ts
  packages/vue-dot/src/patterns/UploadWorkflow/tests/__snapshots__/UploadWorkflow.spec.ts.snap
Labels: bug

#2923 ✨ vue-dot: Add PeriodField component
  packages/docs/src/assets/images/components/period-field.svg
  packages/docs/src/content/composants/formulaires/period-field.md
  packages/docs/src/data/api/period-field.ts
  packages/docs/src/data/componentList.ts
  packages/docs/src/data/drawerItems.ts
  packages/docs/src/data/examples/form-field/period.vue
  packages/docs/src/data/examples/period-field/usage.vue
  packages/form-builder/src/components/FormBuilder/tests/FormBuilder.spec.ts
  packages/form-builder/src/components/FormBuilder/tests/__snapshots__/FormBuilder.spec.ts.snap
  packages/form-builder/src/components/FormBuilder/tests/data/questionForm.ts
  packages/form-builder/src/components/FormField/fields/ChoicePeriodField.vue
  packages/form-builder/src/components/FormField/fields/PeriodField.vue
  packages/form-builder/src/components/FormField/mixins/fieldMap.ts
  packages/form-builder/src/components/FormField/mixins/tests/__snapshots__/fieldMap.spec.ts.snap
  packages/vue-cli-plugin-vue-dash/vueDotLoader.js
  packages/vue-dot/src/patterns/PeriodField/PeriodField.vue
  packages/vue-dot/src/patterns/PeriodField/config.ts
  packages/vue-dot/src/patterns/PeriodField/index.ts
  packages/vue-dot/src/patterns/PeriodField/tests/PeriodField.spec.ts
  packages/vue-dot/src/patterns/PeriodField/tests/__snapshots__/PeriodField.spec.ts.snap
  packages/vue-dot/src/patterns/PeriodField/types.d.ts
  packages/vue-dot/src/patterns/index.ts
  packages/vue-dot/tests/integration/__snapshots__/libTheme.spec.ts.snap
  packages/vue-dot/tests/integration/__snapshots__/plugin.spec.ts.snap
  packages/vue-dot/tests/integration/__snapshots__/registerAllComponents.spec.ts.snap
Labels: refactoring
