Repository assurance-maladie-digital/design-system, pull requests merged in 2024-01, with the labels that each got.

#3256 ✨ vue-dot: Add hide-delete-btn in FileList
  packages/docs/src/data/api/file-list.ts
  packages/vue-dot/src/elements/FileList/FileList.vue
Labels: enhancement

#3270 🐛 vue-dot: Fix btn-href prop not working in ErrorPage
  packages/vue-dot/src/templates/ErrorPage/ErrorPage.vue
Labels: bug

#3274 🐛 vue-dot: Fix field types in RangeField
  packages/vue-dot/src/patterns/RangeField/RangeField.vue
  packages/vue-dot/src/patterns/RangeField/tests/__snapshots__/RangeField.spec.ts.snap
Labels: bug

#3292 💄vue-dot: Fix VAlert font size
  packages/vue-dot/dev/App.vue
  packages/vue-dot/src/styles/variables.scss
Labels: bug

#3316 ✨ vue-dot: Add hide-alert prop in RatingPicker
  packages/docs/src/data/api/rating-picker.ts
  packages/docs/src/data/examples/rating-picker/usage.vue
  packages/vue-dot/src/patterns/RatingPicker/RatingPicker.vue
Labels: enhancement

#3340 🔧 vue-dot: Fix VBtn large font-size
  packages/vue-dot/src/styles/variables.scss
Labels: configuration

#3350 📝 docs: Add more details on slots in HeaderBar
  packages/docs/src/data/api/header-bar.ts
Labels: documentation

#3341 🐛 vue-dot: Fix FilterItem type in filterable mixin
  packages/docs/src/data/api/shared/mixins/filterable.ts
  packages/vue-dot/src/mixins/filterable/index.ts
  packages/vue-dot/src/mixins/filterable/types.d.ts
Labels: bug

#3363 🐛 vue-dot: Fix input event order in DatePicker
  packages/vue-dot/src/mixins/filterable/index.ts
  packages/vue-dot/src/patterns/DatePicker/mixins/dateLogic.ts
  packages/vue-dot/src/patterns/DatePicker/mixins/tests/dateLogic.spec.ts
Labels: bug

#3373 🐛 vue-dot: Fix alert icon & icon slot in AlertWrapper
  packages/vue-dot/src/patterns/AlertWrapper/AlertWrapper.vue
Labels: bug

#3369 🐛 vue-dot: Fix text overflow in ExernalLinks
  packages/vue-dot/src/elements/ExternalLinks/ExternalLinks.vue
  packages/vue-dot/src/elements/ExternalLinks/config.ts
Labels: bug

#3376 ✨ vue-dot: Add show-view-btn prop to UploadWorkflow
  packages/docs/src/content/composants/formulaires/upload-workflow.md
  packages/docs/src/data/api/upload-workflow.ts
  packages/docs/src/data/examples/upload-workflow/view-file.vue
  packages/vue-dot/src/patterns/DatePicker/mixins/tests/dateLogic.spec.ts
  packages/vue-dot/src/patterns/UploadWorkflow/UploadWorkflow.vue
  packages/vue-dot/src/patterns/UploadWorkflow/config.ts
  packages/vue-dot/src/patterns/UploadWorkflow/mixins/tests/uploadWorkflowCore.spec.ts
  packages/vue-dot/src/patterns/UploadWorkflow/mixins/uploadWorkflowCore.ts
  packages/vue-dot/src/patterns/UploadWorkflow/tests/__snapshots__/UploadWorkflow.spec.ts.snap
Labels: enhancement
