Repository assurance-maladie-digital/design-system, pull requests merged in 2024-03, with the labels that each got.

#3387 🐛 vue-dot: Fix reactivity issue in PeriodField
  packages/vue-dot/src/patterns/PeriodField/PeriodField.vue
Labels: bug

#3386 🐛 vue-dot: Fix v-model & styles in LangBtn
  packages/docs/src/assets/images/components/lang-btn.svg
  packages/vue-dot/src/patterns/LangBtn/LangBtn.vue
  packages/vue-dot/src/patterns/LangBtn/config.ts
Labels: bug

#3412 ✨ vue-dot: Add readonly prop in SelectBtnField
  packages/docs/src/data/api/select-btn-field.ts
  packages/vue-dot/src/patterns/SelectBtnField/SelectBtnField.vue
Labels: enhancement

#3413 🐛 vue-dot: Use input event instead of change for v-model in NirField
  packages/docs/src/data/api/nir-field.ts
  packages/vue-dot/src/patterns/NirField/NirField.vue
Labels: bug

#3465 Doc : HomePage + Bridge infos
  packages/docs/src/assets/images/bridge.png
  packages/docs/src/components/DocComponentList.vue
  packages/docs/src/components/drawer/DocDrawerListItem.vue
  packages/docs/src/components/global/DocAlertBridge.vue
  packages/docs/src/components/global/DocHomePageList.vue
  packages/docs/src/components/global/DocRoadmap.vue
  packages/docs/src/components/page/DocTextHighlight.vue
  packages/docs/src/constants/ComponentStatusEnum.ts
  packages/docs/src/content/composants/boutons/back-btn.md
  packages/docs/src/content/composants/boutons/back-to-top-btn.md
  packages/docs/src/content/composants/boutons/copy-btn.md
  packages/docs/src/content/composants/boutons/download-btn.md
  packages/docs/src/content/composants/boutons/france-connect-btn.md
  packages/docs/src/content/composants/boutons/lang-btn.md
  packages/docs/src/content/composants/boutons/user-menu-btn.md
  packages/docs/src/content/composants/donnees/chip-list.md
  packages/docs/src/content/composants/donnees/data-list-group.md
  packages/docs/src/content/composants/donnees/data-list.md
  packages/docs/src/content/composants/feedback/alert-wrapper.md
  packages/docs/src/content/composants/feedback/cookie-banner.md
  packages/docs/src/content/composants/feedback/dialog-box.md
  packages/docs/src/content/composants/feedback/header-loading.md
  packages/docs/src/content/composants/feedback/notification-bar.md
  packages/docs/src/content/composants/feedback/rating-picker.md
  packages/docs/src/content/composants/formulaires/nir-field.md
  packages/docs/src/content/composants/formulaires/phone-field.md
  packages/docs/src/content/composants/layout/page-container.md
  packages/docs/src/content/composants/navigation/contextual-menu.md
  packages/docs/src/content/composants/navigation/external-links.md
  packages/docs/src/content/composants/navigation/skip-link.md
  packages/docs/src/content/composants/structure/footer-bar.md
  packages/docs/src/content/composants/structure/footer-wrapper.md
  packages/docs/src/content/composants/structure/header-bar.md
  packages/docs/src/content/composants/structure/sub-header.md
  packages/docs/src/content/demarrer/introduction.md
  packages/docs/src/content/templates/cookies-page.md
  packages/docs/src/content/templates/error-page.md
  packages/docs/src/content/templates/maintenance-page.md
  packages/docs/src/content/templates/not-found-page.md
  packages/docs/src/data/componentList.ts
  packages/docs/src/data/drawerItems.ts
  packages/docs/src/data/homePageListItems.ts
  packages/docs/src/data/templateList.ts
  packages/docs/src/types/drawer.d.ts
  pnpm-lock.yaml
Labels: documentation

#3418 🐛 vue-dot: Fix tooltip position in NirField
  packages/vue-dot/src/patterns/NirField/NirField.vue
  packages/vue-dot/src/patterns/NirField/tests/__snapshots__/NirField.spec.ts.snap
Labels: bug

#3425 fix compte ameli logo alternative
  packages/vue-dot/src/elements/LogoBrandSection/secondaryLogoMapping.ts
Labels: bug

#3428 ✨vue-dot: Add label slots in RatingPicker components
  packages/docs/src/data/api/rating-picker.ts
  packages/vue-dot/src/patterns/RatingPicker/EmotionPicker/EmotionPicker.vue
  packages/vue-dot/src/patterns/RatingPicker/NumberPicker/NumberPicker.vue
  packages/vue-dot/src/patterns/RatingPicker/RatingMixin.ts
  packages/vue-dot/src/patterns/RatingPicker/RatingPicker.vue
  packages/vue-dot/src/patterns/RatingPicker/StarsPicker/StarsPicker.vue
Labels: enhancement
